### ISSUE TITLE
Unable to upload dashes

### ISSUE THREAD

**Issue by alopes-dn** [Beam-Connectivity/grafana-dashboard-manager#17]
The script fails to upload dashes previously downloaded to another instance. The directories are created, but it fails with:

> [16:32:51] INFO     Writing Router uptime dashboard..                                              dashboard_upload.py:106
>           INFO     Writing SNMP Interface Detail dashboard..                                      dashboard_upload.py:106
>           INFO     Setting home dashboard..                                                       dashboard_upload.py:117
> Request failed - 'HTTP error 404: Dashboard not found'

**Comment by chouzee** [comment]
Today I encountered the same issue. Have you resolved it somehow @alopes-dn ?

**Comment by chan-vince** [comment]
This error should be fixed now with the [most recent](https://pypi.org/project/grafana_dashboard_manager/) release
