### ISSUE TITLE
Self Signed Certs?

### ISSUE THREAD

**Issue by vitosans** [Beam-Connectivity/grafana-dashboard-manager#4]
Any support for self-signed certs? 

`(Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)')))`

**Comment by vitosans** [comment]
Found a workaround with:

`export CURL_CA_BUNDLE=""`

**Comment by chan-vince** [comment]
At the moment the cert verification is automatic but yes self-signed certs should be supported, probably along the lines of a cli flag like how curl does it with `--insecure`. But yes setting that env var will sort it in the meantime 👍

**Comment by biswajitm19** [comment]
Hi @vitosans , Are you able to download dashboards without SSL verify ? can you please send me your command.
